### ISSUE TITLE
Mobilify the site.

### ISSUE THREAD

**Issue by fergyfresh** [fergyfresh/carpool#8]
I would probably start by using okayNav to make the nav bar more accessible for the mobile version. Also increate the fonts for the nav bar so that it is bigger on mobile and desktop because YOLO.

https://github.com/VPenkov/okayNav

**Comment by jeszod** [comment]
![feed](https://cloud.githubusercontent.com/assets/17969485/13907248/6c238fea-eec0-11e5-8aad-7fbe4e2c88d1.png)
![home change group](https://cloud.githubusercontent.com/assets/17969485/13907244/6c21298a-eec0-11e5-8785-f1cd5e7cfc17.png)
![home map view](https://cloud.githubusercontent.com/assets/17969485/13907246/6c21fdb0-eec0-11e5-9ac8-5ae39c4568c2.png)
![profile main page](https://cloud.githubusercontent.com/assets/17969485/13907245/6c21e6fe-eec0-11e5-905e-615797bbdbd6.png)
![welcome](https://cloud.githubusercontent.com/assets/17969485/13907247/6c2292f2-eec0-11e5-8832-64d4ede0375f.png)

**Comment by fergyfresh** [comment]
Close enough. #19.
